:doctype: article
:toc: left
:toclevels: 2
:sectnums:
:sectnumlevels: 3
:eqnums: all

= Tracking Jobs across TLE updates
Dan White <dan.white@valpo.edu>

Ideas on what to do when the TLE gets updated for a previously scheduled job.


== Time of Closest Approach

=== Naive solution
Begin with the original TLE, ground station (latitude, longitude, altitude), and the selected pass times (AOS, TCA, LOS).
According to https://space.stackexchange.com/a/24784[this Space StackExchange answer^], NORAD (now JSpOC) re-computes a TLE when the error between the measured position and the SGP4 prediction is greater than 5 km.
A LEO satellite travels much farther than this over the duration of a pass.

Use subscript~0~ to represent the original data and subscript~1~ for new information derived from the next issued TLE.

[latexmath]
++++
\Delta t_0 = \mathrm{LOS}_0 - \mathrm{AOS}_0\\
++++

If the error between the predictions from the two TLEs is small enough, we can find the congruent pass by finding a new pass which overlaps with the old TCA.

[latexmath]
++++
\mathrm{AOS}_1 < \mathrm{TCA}_0 < \mathrm{LOS}_1
++++

Failing this, the next step would be to find the closest pass to the old TCA within (half of) the orbital period of the satellite.


=== Better solution
The previous approach will not find the appropriate pass when the new passes near the old TCA no longer rise above the station's horizon.
One way to deal with this is to not detect passes by finding horizon crossings, but to use the local maxima of the elevation angle.
See <<Rhodes>> for a discussion of finding these using `python-skyfield`.

Much of the time this curve is negative (below the horizon) -- passes are defined as the intervals where the elevation is positive.
From the list of these maxima (or TCAs), then find the new TCA which is closest in time to the old TCA.

Matching to a new TCA with a negative elevation angle is reason to outright cancel the previously scheduled job.
Otherwise, the job's AOS, TCA, and LOS can be updated to the newly computed values.



[bibliography]
== References

- [[[Rhodes]]] Brandon Rhodes.  https://github.com/skyfielders/astronomy-notebooks/blob/master/Solvers/Earth-Satellite-Passes.ipynb


// vim: textwidth=0
